Homework1__hard-MADE
made-ml-in-prod-2022/Aer-bit pull request #3
Opened 2022-05-16 07:48 UTC by Aer-bit

Ссылка на првый реквест: https://github.com/made-ml-in-prod-2022/Aer-bit/pull/2

Изменения относительно первого реквеста:

1. Добавил датаклассы для сущностей из конфига (2 балла)
2. Добавил пайплайн предобработки данных (использовал готовый класс из sklearn) (2 балла)
3. Добавил Hydra (3 балла)

Суммарно +7баллов.
Итого суммарно 30 баллов.

2022-06-02 06:57 UTC, SVizor42 commented on ml_project/train.py
> +from ml_project.utils import preprocessing_pipeline
Лучше разделять стандартные и локальные импорты. Нужно также проверить остальные модули

2022-06-02 06:57 UTC, SVizor42 commented on ml_project/utils.py
> +def preprocessing_pipeline(input_data_path,
Typing?

2022-06-02 07:02 UTC, SVizor42 commented on ml_project/train.py
> +from ml_project.utils import preprocessing_pipeline
Кстати, некоторые из импортируемых пакетов не используются. Их лучше убрать

2022-06-02 07:17 UTC, SVizor42 commented on ml_project/predict.py
> +    X_test = data[configs.feature_cols]
Тут получается без препроцессинга

2022-06-02 07:22 UTC, SVizor42 requested changes
В целом, все ок. 

Небольшие комментарии:

1. Добавь пожалуйста метку - TECHNOPARK или MADE
2. dvc мне не позволил спулить данные с gdrive. Либо пути поменялись, либо доступа нет (это просто для информации)
3. Еще желательно прогнать код через flake или другой линтер

2022-06-03 06:53 UTC, Aer-bit commented on ml_project/train.py
> +from ml_project.utils import preprocessing_pipeline
Спасибо за замечание, исправил в коде.

2022-06-03 06:55 UTC, Aer-bit commented on ml_project/utils.py
> +def preprocessing_pipeline(input_data_path,
Здесь вроде бы нет опечатки, просто аргументы функции разделил по строкам для лучшей читаемости.

2022-06-03 06:57 UTC, Aer-bit commented on ml_project/predict.py
> +    X_test = data[configs.feature_cols]
Да, здесь упустил этот момент.

2022-06-03 07:08 UTC, Aer-bit commented
Спасибо за ревью. По 3-му пункту, если я правильно понял задание, то прогон через flake у меня реализован через github workflows, код можно увидеть в первом пулл реквесте: https://github.com/made-ml-in-prod-2022/Aer-bit/pull/2.

2022-06-03 09:47 UTC, SVizor42 commented on ml_project/utils.py
> +def preprocessing_pipeline(input_data_path,
Не, я о типах данных у аргументов и возвращаемого значения :)

2022-06-03 10:10 UTC, SVizor42 approved these changes
По поводу flake в Actions - там же фильтр у тебя стоит (что в целом, тоже ок).
Поправь типы и можешь сливать, если нет вопросов по баллам. 

Approved
**Сумма: 24 + 7 * 0.6 = 28.2 балла** (пункт 0 также оценивается, поэтому +1 балл)

2022-06-03 11:35 UTC, Aer-bit commented on ml_project/utils.py
> +def preprocessing_pipeline(input_data_path,
Понял, исправил))

2022-06-03 11:41 UTC, merged